#!/bin/bash

# Quick Start Script for Azure Data Lake Gen2 Deployment
# This script guides you through the deployment process

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

echo "=========================================="
echo "Azure Data Lake Gen2 - Quick Start"
echo "=========================================="
echo ""

# Check prerequisites
echo "Checking prerequisites..."

# Check Terraform
if ! command -v terraform &> /dev/null; then
    echo -e "${RED}✗ Terraform not found${NC}"
    echo "Please install: https://www.terraform.io/downloads"
    exit 1
fi
echo -e "${GREEN}✓ Terraform installed${NC}"

# Check Azure CLI
if ! command -v az &> /dev/null; then
    echo -e "${RED}✗ Azure CLI not found${NC}"
    echo "Please install: https://docs.microsoft.com/cli/azure/install-azure-cli"
    exit 1
fi
echo -e "${GREEN}✓ Azure CLI installed${NC}"

# Check Azure login
if ! az account show &> /dev/null; then
    echo -e "${YELLOW}⚠ Not logged in to Azure${NC}"
    echo "Logging in..."
    az login
fi
echo -e "${GREEN}✓ Azure CLI authenticated${NC}"

# Show current subscription
SUBSCRIPTION=$(az account show --query name -o tsv)
echo -e "${GREEN}✓ Current subscription: ${SUBSCRIPTION}${NC}"
echo ""

# Get public IP
PUBLIC_IP=$(curl -s https://ifconfig.me)
echo -e "Your public IP: ${GREEN}${PUBLIC_IP}${NC}"
echo ""

# Create terraform.tfvars if it doesn't exist
if [ ! -f terraform.tfvars ]; then
    echo "Creating terraform.tfvars..."

    # Generate unique names
    RANDOM_SUFFIX=$(openssl rand -hex 3)
    STORAGE_NAME="stdatalake${RANDOM_SUFFIX}"
    KV_NAME="kv-dl-${RANDOM_SUFFIX}"

    read -p "Enter resource group name [rg-datalake-prod]: " RG_NAME
    RG_NAME=${RG_NAME:-rg-datalake-prod}

    read -p "Enter Azure region [East US]: " LOCATION
    LOCATION=${LOCATION:-"East US"}

    read -p "Enter storage account name [${STORAGE_NAME}]: " STORAGE_INPUT
    STORAGE_NAME=${STORAGE_INPUT:-$STORAGE_NAME}

    read -p "Enter Synapse workspace name [synapse-datalake-prod]: " SYNAPSE_NAME
    SYNAPSE_NAME=${SYNAPSE_NAME:-synapse-datalake-prod}

    read -p "Enter SQL admin username [sqladminuser]: " SQL_USER
    SQL_USER=${SQL_USER:-sqladminuser}

    read -sp "Enter SQL admin password (min 12 chars, complex): " SQL_PASS
    echo ""

    read -p "Add your IP (${PUBLIC_IP}) to Synapse firewall? [Y/n]: " ADD_IP
    ADD_IP=${ADD_IP:-Y}

    if [[ $ADD_IP =~ ^[Yy]$ ]]; then
        CLIENT_IP=$PUBLIC_IP
    else
        CLIENT_IP=""
    fi

    # Create terraform.tfvars
    cat > terraform.tfvars <<EOF
# Terraform Variables - Auto-generated by quickstart.sh

resource_group_name  = "${RG_NAME}"
location             = "${LOCATION}"
storage_account_name = "${STORAGE_NAME}"

storage_account_tier     = "Standard"
storage_replication_type = "LRS"
enable_private_access    = false

synapse_workspace_name     = "${SYNAPSE_NAME}"
synapse_sql_admin_username = "${SQL_USER}"
synapse_sql_admin_password = "${SQL_PASS}"
client_ip_address          = "${CLIENT_IP}"

create_data_factory = true
data_factory_name   = "adf-datalake-prod"

create_key_vault = true
key_vault_name   = "${KV_NAME}"

tags = {
  Environment = "Production"
  Project     = "DataLake"
  ManagedBy   = "Terraform"
}
EOF

    echo -e "${GREEN}✓ Created terraform.tfvars${NC}"
else
    echo -e "${GREEN}✓ terraform.tfvars already exists${NC}"
fi

echo ""
echo "=========================================="
echo "Ready to deploy!"
echo "=========================================="
echo ""

# Initialize Terraform
read -p "Initialize Terraform? [Y/n]: " INIT
INIT=${INIT:-Y}

if [[ $INIT =~ ^[Yy]$ ]]; then
    echo "Initializing Terraform..."
    terraform init
    echo -e "${GREEN}✓ Terraform initialized${NC}"
fi

echo ""

# Plan
read -p "Review deployment plan? [Y/n]: " PLAN
PLAN=${PLAN:-Y}

if [[ $PLAN =~ ^[Yy]$ ]]; then
    echo "Creating deployment plan..."
    terraform plan
fi

echo ""

# Apply
read -p "Deploy infrastructure? [y/N]: " DEPLOY
DEPLOY=${DEPLOY:-N}

if [[ $DEPLOY =~ ^[Yy]$ ]]; then
    echo "Deploying infrastructure..."
    terraform apply -auto-approve

    echo ""
    echo "=========================================="
    echo -e "${GREEN}✓ Deployment complete!${NC}"
    echo "=========================================="
    echo ""

    # Show outputs
    echo "Important endpoints:"
    echo "-------------------"
    terraform output

    echo ""
    echo "Next steps:"
    echo "1. Open Azure Portal to verify resources"
    echo "2. Configure Synapse SQL external tables"
    echo "3. Connect Power BI to Synapse endpoint"
    echo "4. Set up data ingestion pipelines"
    echo ""
    echo "See README.md for detailed instructions"
else
    echo "Deployment skipped. Run 'terraform apply' when ready."
fi
